# Generated by Django 4.1.3 on 2022-12-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('face', models.CharField(max_length=100000)),
                ('img', models.CharField(max_length=500)),
            ],
        ),
    ]
